# Generated by Django 5.0.7 on 2024-07-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_rol_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
    ]
