# Generated by Django 5.0.7 on 2024-07-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_rol_permisos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioRolPermiso',
        ),
    ]
